<?php

use Drupal\Core\Url;
use Drupal\Core\Render\Markup;

/**
 * Implements hook_toolbar_alter().
 */
function myseo_toolbar_alter(&$items) {
  $items['administration']['#attached']['library'][] = 'myseo/toolbar';
}


/**
 * Implements hook_cron().
 */
function myseo_cron() {
  // Удаляем файл robots.txt в корне сайта, если вкл. модуль robotstxt
  if (\Drupal::moduleHandler()->moduleExists('robotstxt')) {
    if (file_exists('./robots.txt')) {
      unlink('./robots.txt');
    }
  }
}


/**
 * Implements hook_preprocess_pager().
 */
function myseo_preprocess_pager(&$variables) {
  // Remove "?page=0" from pager href
  $route_parameters = isset($variables['pager']['#route_parameters']) ? $variables['pager']['#route_parameters'] : [];
  /* @var $request \Symfony\Component\HttpFoundation\Request */
  $request = \Drupal::request();
  $is_ajax = $request->isXmlHttpRequest();
  $href = '?';
  if (!$is_ajax) {
    $href = Url::fromRoute('<current>', $route_parameters);
  }
  if (!empty($variables['items']['first']['href']) && $variables['items']['first']['href'] == '?page=0') {
    $variables['items']['first']['href'] = $href;
  }
  if (!empty($variables['items']['previous']['href']) && $variables['items']['previous']['href'] == '?page=0') {
    $variables['items']['previous']['href'] = $href;
  }
  if (!empty($variables['items']['pages'])) {
    foreach ($variables['items']['pages'] as $key => $page) {
      if ($page['href'] == '?page=0') {
        $variables['items']['pages'][$key]['href'] = $href;
      }
    }
  }
}


/**
 * Implements hook_preprocess_html().
 */


function myseo_preprocess_html(&$variables) {
  // Добавляем html-regions
  $config = Drupal::config('myseo.html_regions');
  $myseo_head = !empty($config->get('myseo_head')) ? $config->get('myseo_head') : '';
  $myseo_body_top = !empty($config->get('myseo_body_top')) ? $config->get('myseo_body_top') : '';
  $myseo_body_bottom = !empty($config->get('myseo_body_bottom')) ? $config->get('myseo_body_bottom') : '';
  $variables['myseo_head'] = [
    '#markup' => Markup::create($myseo_head),
  ];
  $variables['myseo_body_top'] = [
    '#markup' => Markup::create($myseo_body_top),
  ];
  $variables['myseo_body_bottom'] = [
    '#markup' => Markup::create($myseo_body_bottom),
  ];
}
