<?php

use Drupal\Core\Url;

/**
 * Implements hook_toolbar_alter().
 */
function myseo_toolbar_alter(&$items) {
  $items['administration']['#attached']['library'][] = 'myseo/toolbar';
}


/**
 * Implements hook_cron().
 */
function myseo_cron() {
  // Удаляем файл robots.txt в корне сайта, если вкл. модуль robotstxt
  if (\Drupal::moduleHandler()->moduleExists('robotstxt')) {
    if (file_exists('./robots.txt')) {
      unlink('./robots.txt');
    }
  }
}


/**
 * Implements hook_preprocess_pager().
 */
function myseo_preprocess_pager(&$variables) {
  // Remove "?page=0" from pager href
  $route_parameters = isset($variables['pager']['#route_parameters']) ? $variables['pager']['#route_parameters'] : [];
  if (!empty($variables['items']['first']['href']) && $variables['items']['first']['href'] == '?page=0') {
    $variables['items']['first']['href'] = Url::fromRoute('<current>', $route_parameters);
  }
  if (!empty($variables['items']['previous']['href']) && $variables['items']['previous']['href'] == '?page=0') {
    $variables['items']['previous']['href'] = Url::fromRoute('<current>', $route_parameters);
  }
  if (!empty($variables['items']['pages'])) {
    foreach ($variables['items']['pages'] as $key => $page) {
      if ($page['href'] == '?page=0') {
        $variables['items']['pages'][$key]['href'] = Url::fromRoute('<current>', $route_parameters);
      }
    }
  }
}


